apiVersion: v1
kind: Secret
metadata:
  name: magnetixdian-secrets
  namespace: magnetixdian
type: Opaque
stringData:
  DB_URL: jdbc:postgresql://db:5432/magnetixdian?characterEncoding=UTF-8
  DB_USER: magnetixdian
  DB_PASSWORD: magnetixdian
  JWT_SECRET: bWFnbmV0aXhkaWFuLXN1cGVyLXNlY3JldC1rZXktZm9yLWp3dC1zaWduaW5nLTIwMjYtcGt6ZDEyM2ZiYQ==
  POSTGRES_DB: magnetixdian
  POSTGRES_USER: magnetixdian
  POSTGRES_PASSWORD: magnetixdian